# Generated by Django 4.2.7 on 2023-11-29 18:01 generacion de la base de datos.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('calorias', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
    ]
